# Generated by Django 5.2.14 on 2026-05-26 19:57
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # última migration do users que ainda tem o MemberChurch
        ("users", "0005_memberchurch_role_alter_memberchurch_status_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Nenhuma alteração real no banco — a tabela users_memberchurch já existe
            database_operations=[],

            # Apenas atualiza o estado interno do Django:
            # "o model MemberChurch agora pertence ao app community"
            state_operations=[
                migrations.CreateModel(
                    name="MemberChurch",
                    fields=[
                        ("id", models.BigAutoField(
                            auto_created=True, primary_key=True,
                            serialize=False, verbose_name="ID",
                        )),
                        ("role", models.CharField(
                            choices=[
                                ("member",       "Membro"),
                                ("pastor/padre", "Pastor/Padre"),
                                ("tesoureiro",   "Tesoureiro"),
                                ("secretário",   "Secretário"),
                                ("admin",        "Administrador"),
                            ],
                            db_index=True, default="member",
                            max_length=30, verbose_name="Função",
                        )),
                        ("status", models.CharField(
                            choices=[
                                ("active",   "Ativo"),
                                ("inactive", "Inativo"),
                                ("pending",  "Pendente"),
                            ],
                            db_index=True, default="pending",
                            max_length=20, verbose_name="Status",
                        )),
                        ("joined_at", models.DateTimeField(
                            auto_now_add=True,
                            help_text="Data e hora em que o membro se vinculou à igreja.",
                            verbose_name="Data de adesão",
                        )),
                        ("left_at", models.DateTimeField(
                            blank=True, null=True,
                            help_text="Data e hora em que o membro se desvinculou da igreja. Deixe em branco se ainda for membro.",
                            verbose_name="Data de saída",
                        )),
                        ("member", models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="church_memberships",
                            to="users.member",
                        )),
                        ("church", models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="member_memberships",
                            to="users.church",
                        )),
                    ],
                    options={
                        "verbose_name":        "Vínculo Membro-Igreja",
                        "verbose_name_plural": "Vínculos Membro-Igreja",
                        "db_table":            "users_memberchurch",
                        "ordering":            ["-joined_at"],
                    },
                ),
                migrations.AddConstraint(
                    model_name="memberchurch",
                    constraint=models.UniqueConstraint(
                        fields=["member", "church"],
                        name="unique_member_church",
                    ),
                ),
            ],
        )
    ]