# Generated by Django 5.2.14 on 2026-05-27 22:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberChurch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Membro'), ('pastor/padre', 'Pastor/Padre'), ('tesoureiro', 'Tesoureiro'), ('secretário', 'Secretário'), ('admin', 'Administrador')], db_index=True, default='member', max_length=30, verbose_name='Função')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('pending', 'Pendente')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o membro se vinculou à igreja.', verbose_name='Data de adesão')),
                ('left_at', models.DateTimeField(blank=True, help_text='Data e hora em que o membro se desvinculou da igreja. Deixe em branco se ainda for membro.', null=True, verbose_name='Data de saída')),
            ],
            options={
                'verbose_name': 'Vínculo Membro-Igreja',
                'verbose_name_plural': 'Vínculos Membro-Igreja',
                'ordering': ['-joined_at'],
            },
        ),
    ]
