# Generated by Django 5.2.14 on 2026-05-27 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberchurch',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_memberships', to='users.church'),
        ),
        migrations.AddField(
            model_name='memberchurch',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_memberships', to='users.member'),
        ),
        migrations.AddIndex(
            model_name='memberchurch',
            index=models.Index(fields=['member', 'church'], name='community_m_member__208e90_idx'),
        ),
        migrations.AddIndex(
            model_name='memberchurch',
            index=models.Index(fields=['church', 'role'], name='community_m_church__b1cb72_idx'),
        ),
        migrations.AddIndex(
            model_name='memberchurch',
            index=models.Index(fields=['church', 'status'], name='community_m_church__14504b_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberchurch',
            constraint=models.UniqueConstraint(fields=('member', 'church'), name='unique_member_church'),
        ),
        migrations.AlterUniqueTogether(
            name='memberchurch',
            unique_together={('member', 'church')},
        ),
    ]
