# Generated by Django 5.2.14 on 2026-05-15 19:05

import dizimus.apps.users.validators
import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='church',
        ),
        migrations.AddField(
            model_name='church',
            name='about',
            field=models.TextField(blank=True, help_text='Descrição da igreja. Máx: 1000 caracteres.', null=True, verbose_name='Sobre'),
        ),
        migrations.AddField(
            model_name='church',
            name='asaas_token',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Token de acesso à API do Asaas.', null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='church',
            name='total_members',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total de membros'),
        ),
        migrations.AddField(
            model_name='church',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='church',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Formato: 00.000.000/0000-00.', max_length=18, null=True, unique=True, validators=[dizimus.apps.users.validators.validate_cnpj]),
        ),
        migrations.AlterField(
            model_name='member',
            name='cpf',
            field=models.CharField(blank=True, help_text='Formato: 000.000.000-00.', max_length=14, null=True, unique=True, validators=[dizimus.apps.users.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sobrenome'),
        ),
        migrations.CreateModel(
            name='MemberChurch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('pending', 'Pendente')], default='pending', max_length=20, verbose_name='Status')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o membro se vinculou à igreja.', verbose_name='Data de adesão')),
                ('left_at', models.DateTimeField(blank=True, help_text='Data e hora em que o membro se desvinculou da igreja. Deixe em branco se ainda for membro.', null=True, verbose_name='Data de saída')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_memberships', to='users.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_memberships', to='users.member')),
            ],
            options={
                'verbose_name': 'Vínculo Membro-Igreja',
                'verbose_name_plural': 'Vínculos Membro-Igreja',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['member', 'church'], name='users_membe_member__0f751c_idx')],
                'unique_together': {('member', 'church')},
            },
        ),
    ]
