# Generated by Django 5.2.14 on 2026-06-01 21:26

import dizimus.apps.users.validators.validate_cpf_cnpj
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='church',
            name='church_type',
            field=models.CharField(choices=[('headquarters', 'Sede/Matriz'), ('community', 'Comunidade'), ('independent', 'Independente')], default='independent', max_length=20),
        ),
        migrations.AddField(
            model_name='church',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Ex: Igreja Batista da Paz.', max_length=255, null=True, verbose_name='Nome Completo da Instituição'),
        ),
        migrations.AddField(
            model_name='church',
            name='parent_church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_churches', to='users.church'),
        ),
        migrations.AddField(
            model_name='church',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='contribution_type',
            field=models.CharField(choices=[('none', 'Nenhum'), ('dizimista', 'Dizimista'), ('ofertante', 'Ofertante'), ('both', 'Dizimista e Ofertante')], default='none', max_length=20, verbose_name='Tipo de contribuição'),
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Primeiro nome'),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nome de usuário'),
        ),
        migrations.AlterField(
            model_name='church',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Formato: 00.000.000/0000-00.', max_length=18, null=True, validators=[dizimus.apps.users.validators.validate_cpf_cnpj.validate_cnpj]),
        ),
        migrations.AddConstraint(
            model_name='church',
            constraint=models.UniqueConstraint(fields=('cnpj', 'full_name'), name='unique_church_per_cnpj_name'),
        ),
    ]
