# Generated by Django 5.2.14 on 2026-05-17 20:10

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_member_church_church_about_church_asaas_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Número de telefone no formato internacional, ex: +55 11 99999-8888.', max_length=128, region='BR'),
        ),
    ]
