# Generated by Django 5.2.14 on 2026-05-27 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_memberchurch_role_alter_memberchurch_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberChurch',
        ),
    ]
